@startuml C4-Context-YaQuedo
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title C4 · Nivel 1 (Contexto) — YaQuedo

Person(cliente, "Cliente", "Usuario que gestiona su cuenta y hace busquedas de tecnicos en funcion al servicio que requiere.")
Person(trabajador, "Trabajador", "Usuario que gestiona su cuenta y publica sus servicios tecnicos de hogar.")

System(yaquedo, "YaQuedo", "Plataforma labtech que se encarga de conectar usuarios urbanos con trabajadores tecnicos de hogar.")

System_Ext(ia, "Servicio IA", "Asistente conversacional Llama 3.3 70B via Groq")
System_Ext(osm, "OpenStreetMap", "Provee servicios de mapas, ubicacion y geolocalizacion")
System_Ext(smtp, "Gmail SMTP", "Permite validar la pertenencia del correo del usuario")

Rel(cliente, yaquedo, "Gestionar busquedas en funcion a ubicacion, servicios y costos")
Rel(trabajador, yaquedo, "Publicar su perfil en funcion a ubicacion, servicios y costos")

Rel(yaquedo, ia, "Consulta asistente", "JSON + HTTP")
Rel(yaquedo, osm, "Consulta ubicacion", "JSON + HTTP")
Rel(yaquedo, smtp, "Consulta verificacion email", "JSON + HTTP(frontend & Spring Boot) / SMTP")

@enduml
